events {}

http {
  upstream node { server node:3000; }
  upstream python { server python:8000; }
  upstream java { server java:8080; }

  server {
    listen 80;

    location / {
      proxy_pass http://node;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /python/ {
      rewrite ^/python(/.*)$ $1 break;
      proxy_pass http://python;
      proxy_set_header Host $host;
    }

    location /java/ {
      rewrite ^/java(/.*)$ $1 break;
      proxy_pass http://java;
      proxy_set_header Host $host;
    }
  }
}
